/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/authentication`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | ``; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/searchPage` | `/searchPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/[username]` | `/[username]`, params: Router.UnknownInputParams & { username: string | number; } } | { pathname: `${'/(app)'}/artPostDetails/[id]` | `/artPostDetails/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/authentication`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | ``; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/searchPage` | `/searchPage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/[username]` | `/[username]`, params: Router.UnknownOutputParams & { username: string; } } | { pathname: `${'/(app)'}/artPostDetails/[id]` | `/artPostDetails/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/authentication${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/searchPage${`?${string}` | `#${string}` | ''}` | `/searchPage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/authentication`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | ``; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/searchPage` | `/searchPage`; params?: Router.UnknownInputParams; } | `${'/(app)'}${'/(tabs)'}/${Router.SingleRoutePart<T>}` | `/${Router.SingleRoutePart<T>}` | `${'/(app)'}/artPostDetails/${Router.SingleRoutePart<T>}` | `/artPostDetails/${Router.SingleRoutePart<T>}` | { pathname: `${'/(app)'}${'/(tabs)'}/[username]` | `/[username]`, params: Router.UnknownInputParams & { username: string | number; } } | { pathname: `${'/(app)'}/artPostDetails/[id]` | `/artPostDetails/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
